server:
  port: 9991

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #使用服务名称调用
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: test1
          uri: lb://platform-managersystem
          predicates:
            - Path=/antaourl/**
          #过滤配置，剥离前缀 antaourl
          filters:
            - StripPrefix=1
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: springcloud-gateway-9991 #修改eureka上面的默认描述信息


