server:
  port: 9992

spring:
  application:
    name: platform-oauth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

#eureka服务注册配置
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      #（单个eureka服务发布）defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-oauth-9992 #修改eureka上面的默认描述信息