server:
  port: 8085

spring:
  application:
    name: platform-managersystem
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456


#eureka服务注册配置
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:

      #（单个eureka服务发布）defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: springcloud-managersystem-8085 #修改eureka上面的默认描述信息

info:
  app.name: platform-managersystem
  user.name: antao